@startuml diagram
class ModelicaModel{
    package_name: str
    model_name: str
    settings: dict
    components: list<MS4VCObject>
    add_component(MS4VCObject): void
    map_components(): void
    map_connectors(): void
    write_modelica_package(): str
    write_modelica_files(): str
    modelica_model_file: str
    modelica_package_file: str
}
ModelicaModel "1" -- "1..*" MS4VCObject
class MS4VCObject {
    FSC_component: FSCObject
    medium: str
    component_string: str
    port_names: dict
    instantiated_connections: dict
    find_medium(): str
    create_port_names(): void
    get_output_port(): str
    get_input_port(): str
    connect_component(): void
    calculate_diameters(): list<float>
    ispropin(): str
}

class Radiator {
  model_template
  portnames = ["port_a", "port_b"]
}
MS4VCObject <|-- Radiator

class FlowSegment {
  model_template
  portnames = ["port_a", "port_b"]
}
MS4VCObject <|-- FlowSegment


@enduml